@tool
extends Node

const SIZE : float = 600.

@onready var dome : Dome = %Dome
@onready var hex_map : HexMap = %HexMap
@onready var alien_horde_manager : AlienHordeManager = %AlienHordeManager
@onready var game_gui : GameGui = %GameGui
@onready var spawners : Node = %Spawners

@export_tool_button("Init Game", "Callable") var load_map_action = init_game
var wave

func _ready():
    init_game()

func init_game():
    dome.size = SIZE
    hex_map.radius = roundi(SIZE / (HexTile.BASE_TILE_SIZE * 2)) - 1
    hex_map.load_map()

